gestion/urls.py
from django.conf.urls import url
from . import views

app_name = 'gestion'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<companie_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<employee_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^employees/(?P<filter_by>[a-zA_Z]+)/$', views.employees, name='employees'),
    url(r'^create_companie/$', views.create_companie, name='create_companie'),
    url(r'^(?P<companie_id>[0-9]+)/create_employee/$', views.create_employee, name='create_employee'),
    url(r'^(?P<companie_id>[0-9]+)/delete_employee/(?P<employee_id>[0-9]+)/$', views.delete_employee, name='delete_employee'),
    url(r'^(?P<companie_id>[0-9]+)/favorite_companie/$', views.favorite_companie, name='favorite_companie'),
    url(r'^(?P<companie_id>[0-9]+)/delete_companie/$', views.delete_companie, name='delete_companie'),
]

yourCRM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gestion.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

class Companie(models.Model):
    user = models.ForeignKey(User, default=1)
    companie_name = models.CharField(max_length=250)
    address = models.CharField(max_length=500)
    companie_logo = models.FileField()

    def __str__(self):
        return self.companie_name

class Employee(models.Model):
    companie = models.ForeignKey(Companie, on_delete=models.CASCADE)
    employee_name = models.CharField(max_length=250)
    employee_surname = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.employee_name + ' ' + self.employee_surname

gestion/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Companie, Employee

class CompanieForm(forms.ModelForm):

    class Meta:
        model = Companie
        fields = ['companie_name', 'address', 'companie_logo']

class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['employee_name', 'employee_surname']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

gestion/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import CompanieForm, EmployeeForm, UserForm
from .models import Companie, Employee

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_companie(request):
    if not request.user.is_authenticated():
        return render(request, 'gestion/login.html')
    else:
        form = CompanieForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            companie = form.save(commit=False)
            companie.user = request.user
            companie.companie_logo = request.FILES['companie_logo']
            file_type = companie.companie_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'companie': companie,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'gestion/create_companie.html', context)
            companie.save()
            return render(request, 'gestion/detail.html', {'companie': companie})
        context = {
            "form": form,
        }
        return render(request, 'gestion/create_companie.html', context)


def create_employee(request, companie_id):
    form = EmployeeForm(request.POST or None)
    companie = get_object_or_404(Companie, pk=companie_id)
    if form.is_valid():
        employee = form.save(commit=False)
        employee.companie = companie
        employee.save()
        return render(request, 'gestion/detail.html', {'companie': companie})
    context = {
        'companie': companie,
        'form': form,
    }
    return render(request, 'gestion/create_employee.html', context)


def delete_companie(request, companie_id):
    companie = Companie.objects.get(pk=companie_id)
    companie.delete()
    companie = Companie.objects.filter(user=request.user)
    return render(request, 'gestion/index.html', {'companie': companie})


def delete_employee(request, companie_id, employee_id):
    companie = get_object_or_404(Companie, pk=companie_id)
    employee = Employee.objects.get(pk=employee_id)
    employee.delete()
    return render(request, 'gestion/detail.html', {'companie': companie})


def detail(request, companie_id):
    if not request.user.is_authenticated():
        return render(request, 'gestion/login.html')
    else:
        user = request.user
        companie = get_object_or_404(Companie, pk=companie_id)
        return render(request, 'gestion/detail.html', {'companie': companie, 'user': user})


def favorite(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    try:
        if employee.is_favorite:
            employee.is_favorite = False
        else:
            employee.is_favorite = True
        employee.save()
    except (KeyError, Employee.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_companie(request, companie_id):
    companie = get_object_or_404(Companie, pk=companie_id)
    try:
        if companie.is_favorite:
            companie.is_favorite = False
        else:
            companie.is_favorite = True
        companie.save()
    except (KeyError, Companie.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'gestion/login.html')
    else:
        companies = Companie.objects.filter(user=request.user)
        employee_results = Employee.objects.all()
        query = request.GET.get("q")
        if query:
            companies = companies.filter(
                Q(companie_name__icontains=query) |
                Q(address__icontains=query)
            ).distinct()
            employee_results = employee_results.filter(
                Q(employee_name__icontains=query) |
                Q(employee_surname__icontains=query)
            ).distinct()
            return render(request, 'gestion/index.html', {
                'companies': companies,
                'employee': employee_results,
            })
        else:
            return render(request, 'gestion/index.html', {'companies': companies})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'gestion/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                companie = Companie.objects.filter(user=request.user)
                return render(request, 'gestion/index.html', {'companie': companie})
            else:
                return render(request, 'gestion/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'gestion/login.html', {'error_message': 'Invalid login'})
    return render(request, 'gestion/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                companie = Companie.objects.filter(user=request.user)
                return render(request, 'gestion/index.html', {'companie': companie})
    context = {
        "form": form,
    }
    return render(request, 'gestion/register.html', context)


def employees(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'gestion/login.html')
    else:
        try:
            employee_id = []
            for companie in Companie.objects.filter(user=request.user):
                for employee in companie.employee_set.all():
                    employee_id.append(employee.pk)
            users_employee = Employee.objects.filter(pk__in=employee_id)
            if filter_by == 'favorites':
                users_employee = users_employee.filter(is_favorite=True)
        except Companie.DoesNotExist:
            users_employee = []
        return render(request, 'gestion/employees.html', {
            'employee_list': users_employee,
            'filter_by': filter_by,
        })

gestion/templates/gestion/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}YourCRM{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'gestion/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gestion:index' %}">YourCRM</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block companies_active %}{% endblock %}"><a href="{% url 'gestion:index' %}"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp; Companies</a></li>
                <li class="{% block employees_active %}{% endblock %}"><a href="{% url 'gestion:employees' 'all' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Employees</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'gestion:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'gestion:create_companie' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Companie
                    </a>
                </li>
                <li>
                    <a href="{% url 'gestion:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

gestion/templates/gestion/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}YourCRM{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'gestion/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'gestion/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gestion:index' %}">YourCRM</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'gestion:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'gestion:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

gestion/templates/gestion/create_employee.html
{% extends 'gestion/base.html' %}
{% block title %}Add a New Employee{% endblock %}
{% block companies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Companie Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'gestion:detail' companie.id %}">
                            {% if companie.companie_logo %}
                                <img src="{{ companie.companie_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ companie.companie_name }}</h1>
                    <h2>{{ companie.address }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Employee Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'gestion:detail' companie.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'gestion:create_employee' companie.id %}">Add New Employee</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Employee</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="companie" value="{{ album }}">
                        {% include 'gestion/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

gestion/templates/gestion/detail.html
{% extends 'gestion/base.html' %}
{% block title %}{{ companie }}{% endblock %}
{% block companies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Companie Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'gestion:detail' companie.id %}">
                        {% if companie.companie_logo %}
                            <img src="{{ companie.companie_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ companie.companie_name }}</h1>
                    <h2>{{ companie.address }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Employee Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'gestion:detail' companie.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'gestion:create_employee' companie.id %}">Add New Employee</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Employees</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Surname</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for employee in companie.employee_set.all %}
                            <tr>
                                <td>{{ employee.employee_name }}</td>
                                <td>{{ employee.employee_surname }}</td>
                                <td>
                                    <a href="{% url 'gestion:favorite' employee.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if employee.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'gestion:delete_employee' companie.id employee.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="employee_id" value="{{ employee.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

gestion/templates/gestion/employees.html
{% extends 'gestion/base.html' %}
{% block title %}All Employees{% endblock %}
{% block employees_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'gestion:employees' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'gestion:employees' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Surname</th>
                                <th>Companie</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for employee in employee_list %}
                                <tr>
                                    <td>{{ employee.employee_name }}</td>
                                    <td>{{ employee.employee_surname }}</td>
                                    <td>
                                        <a href="{% url 'gestion:detail' employee.companie.id %}">
                                            <img src="{{ employee.companie.companie_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'gestion:detail' employee.companie.id %}">{{ employee.companie.companie_name }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'gestion:favorite' employee.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if employee.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

gestion/templates/gestion/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

gestion/templates/gestion/index.html
{% extends 'gestion/base.html' %}
{% block companies_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Companies</h3>
        </div>
        {% if companies %}
            {% for companie in companies %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'gestion:detail' companie.id %}">
                            <img src="{{ companie.companie_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ companie.companie_name }}</h2>
                            <h4>{{ companie.address }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'gestion:detail' companie.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Companies -->
                            <form action="{% url 'gestion:delete_companie' companie.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="companie_id" value="{{ companie.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'gestion:favorite_companie' companie.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if companie.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'gestion:create_companie' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Companie
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if employees %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Employees</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Surname</th>
                                    <th>Companie</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for employee in employees %}
                                    <tr>
                                        <td>{{ employee.employee_name }}</td>
                                        <td>{{ employee.employee_surname }}</td>
                                        <td>
                                            <a href="{% url 'gestion:detail' employee.companie.id %}">
                                                <img src="{{ employee.companie.companie_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'gestion:detail' employee.companie.id %}">{{ employee.companie.companie_name }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'gestion:favorite' employee.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if employee.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

gestion/templates/gestion/login.html
{% extends 'gestion/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'gestion:login_user' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'gestion:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

gestion/templates/gestion/register.html
{% extends 'gestion/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'gestion/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'gestion:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}